#!/usr/bin/env bash
cd "${0%/*}"

# Cleanup target directory
rm -r target
mkdir target
mkdir target/tmp

# Preprocessing stage (for personnal info section)
xsltproc --output target/tmp/cv-preprocessed.xml cv-preprocess.xsl cv-data.xml

# Generate HTML output
mkdir target/html
cp cv.css target/html/cv.css
xsltproc --output target/html/cv-html.html cv-html.xsl target/tmp/cv-preprocessed.xml

# Generate PDF output
mkdir target/pdf
xsltproc --output target/tmp/cv-fo.fo cv-fo.xsl target/tmp/cv-preprocessed.xml
fop target/tmp/cv-fo.fo target/pdf/cv-fo.pdf
